// Generated by scripts/import-context-log.mjs from ~/.mcpproxy/context.jsonl — do not edit.
// The local mcpproxy gates every mutating Aiven MCP call behind a written purpose; this is the
// captured log for project data-innovation-summit. The Changes tab prefers live data when the proxy is running.
import type { ContextChange } from '@/types'

export const contextLogCapturedAt = '2026-09-04T12:05:41.806Z'

export const contextLog: ContextChange[] = [
  {
    "id": 2,
    "serviceId": "crm-pg",
    "version": 1,
    "operation": "create",
    "toolName": "aiven_service_create",
    "purpose": "User asked to deploy a one-person CRM in this project on a cheap Postgres plan. Creating a dedicated hobbyist database so the app has its own store without sharing existing services.",
    "status": "ok",
    "createdAt": "2026-09-04T08:42:19.837Z",
    "durationMs": 1336,
    "clientName": "cursor-vscode"
  },
  {
    "id": 3,
    "serviceId": "crm-app",
    "version": 1,
    "operation": "deploy",
    "toolName": "aiven_application_deploy",
    "purpose": "User asked to deploy a simple authenticated one-person CRM on a cheap Aiven runtime, connected to the dedicated hobbyist Postgres created for this app.",
    "status": "ok",
    "createdAt": "2026-09-04T08:51:22.879Z",
    "durationMs": 709,
    "clientName": "cursor-vscode"
  },
  {
    "id": 4,
    "serviceId": "crm-app",
    "version": 2,
    "operation": "redeploy",
    "toolName": "aiven_application_redeploy",
    "purpose": "User asked to ship follow-up dates and on-card stage changes on the already deployed one-person CRM. Redeploy picks up the pushed code on the existing app service.",
    "status": "ok",
    "createdAt": "2026-09-04T09:15:38.425Z",
    "durationMs": 245,
    "clientName": "cursor-vscode"
  },
  {
    "id": 5,
    "serviceId": "crm-app",
    "version": 3,
    "operation": "redeploy",
    "toolName": "aiven_application_redeploy",
    "purpose": "User asked to ship the remaining CRM features on the existing app. Redeploy picks up the pushed totals, notes, lost-reason, and CSV changes.",
    "status": "ok",
    "createdAt": "2026-09-04T10:02:47.619Z",
    "durationMs": 425,
    "clientName": "cursor-vscode"
  },
  {
    "id": 6,
    "serviceId": "crm-sql",
    "version": 1,
    "operation": "deploy",
    "toolName": "aiven_application_deploy",
    "purpose": "User asked for a basic UI query editor/runner as another Aiven application runtime on the same PostgreSQL used by the CRM. This creates that service so they can log in and run SQL against crm-pg without using psql or the CRM UI.",
    "status": "ok",
    "createdAt": "2026-09-04T10:21:04.421Z",
    "durationMs": 658,
    "clientName": "cursor-vscode"
  },
  {
    "id": 7,
    "serviceId": "crm-app",
    "version": 4,
    "operation": "redeploy",
    "toolName": "aiven_application_redeploy",
    "purpose": "User asked to improve the CRM with three features, deployed one at a time without waiting for confirmation between them. This first redeploy ships due-item snooze (+1 day / +1 week) after the code was pushed to the configured branch.",
    "status": "ok",
    "createdAt": "2026-09-04T10:39:20.866Z",
    "durationMs": 312,
    "clientName": "cursor-vscode"
  },
  {
    "id": 8,
    "serviceId": "crm-app",
    "version": 5,
    "operation": "redeploy",
    "toolName": "aiven_application_redeploy",
    "purpose": "User asked for three CRM features deployed one at a time. This second redeploy ships automatic notes when an account stage changes, after snooze was already live.",
    "status": "ok",
    "createdAt": "2026-09-04T10:58:01.762Z",
    "durationMs": 411,
    "clientName": "cursor-vscode"
  },
  {
    "id": 9,
    "serviceId": "crm-app",
    "version": 6,
    "operation": "redeploy",
    "toolName": "aiven_application_redeploy",
    "purpose": "User asked for three CRM features deployed one at a time. This third redeploy ships the quiet/stale deals strip after snooze and stage notes were already live.",
    "status": "ok",
    "createdAt": "2026-09-04T11:15:04.519Z",
    "durationMs": 369,
    "clientName": "cursor-vscode"
  },
  {
    "id": 10,
    "serviceId": "capy-store",
    "version": 1,
    "operation": "deploy",
    "toolName": "aiven_application_deploy",
    "purpose": "User asked for another application on the same PostgreSQL: a demo store for capybara-related items. This creates that public shop runtime so they can browse catalog, cart, and demo checkout against crm-pg.",
    "status": "error",
    "createdAt": "2026-09-04T11:52:01.648Z",
    "errorText": "`purpose` restates the user request. Rewrite it as a handoff for the next agent. Bad: \"User asked to deploy a CRM on cheap Postgres.\" Good: \"Asset: Postgres 17 hobbyist crm-pg in aws-eu-west-1; dedicated store for crm-app. Change: creating service plan=hobbyist pg_version=17. Operate: crm-app and crm-sql connect via DATABASE_URL integration; do not share this instance or change plan without checking them.\" Handoff for the next agent that will work on this resource. Write three labeled parts: Asset — what this resource is (type, role, related services); Change — the concrete mutation in THIS call (service/topic/table names, plan, version, cloud, repo/branch/path, config keys, SQL objects); Operate — how to use it next (integrations, env var NAMES only, constraints, what not to break). Do not mention the user request. Do not start with \"User asked\". Do not restate the tool name. No secrets, passwords, tokens, or connection URIs. Then retry this call.",
    "clientName": "cursor-vscode"
  },
  {
    "id": 11,
    "serviceId": "capy-store",
    "version": 2,
    "operation": "deploy",
    "toolName": "aiven_application_deploy",
    "purpose": "Asset: Aiven application capy-store, a public demo shop sharing crm-pg with crm-app and crm-sql. Change: create application plan=startup-50-1024 cloud=aws-eu-west-1 from repo branch main build_path ./store port 3000, integrate pg crm-pg as DATABASE_URL, no VPC. Operate: app reads DATABASE_URL and PROJECT_CA_CERT; creates store_products and store_orders; do not alter crm-pg plan or drop CRM tables.",
    "status": "ok",
    "createdAt": "2026-09-04T11:52:08.802Z",
    "durationMs": 835,
    "clientName": "cursor-vscode"
  }
]
